create table if not exists user_sessions
(
    id          bigint generated by default as identity,
    exp timestamptz not null,
    user_id bigint      not null references users (id) on delete cascade
);

alter table user_sessions
    add constraint user_sessions_id_pk primary key (id);
